### ISSUE TITLE
リポジトリのAboutを設定しませんか

### ISSUE THREAD

**Issue by gpsnmeajp** [nostr-jp/welcome-nostr#18]
Googleのインデックスで、githubのREADMEが登録されている現状を鑑みて、Aboutを設定しませんか？
Aboutが検索エンジンの本文部分に表示されます。

今は設定されていないので、githubの汎用文が表示されています。
![image](https://github.com/nostr-jp/welcome-nostr/assets/33391403/d048b764-dc86-45b7-8956-5f99920820de)

**Comment by penpenpng** [comment]
readme の一文を移してきただけのものですが、設定しました
