### ISSUE TITLE
モバイルアプリでは「秘密鍵でログイン」せざるを得ないことの追記が必要ではないか

### ISSUE THREAD

**Issue by Memory-of-Snow** [nostr-jp/welcome-nostr#7]
「お気に入りのクライアントを探そう」の「ログイン方法の違いについて理解する」において、
「結論だけ先に述べると「秘密鍵でログイン」すべきではありません。」と記載されている。

これを、
「結論だけ先に述べると「秘密鍵でログイン」すべきではありません。
（しかしながら、（多くの）スマートフォンアプリでは秘密鍵でしかログインできません。）」

に変更したほうが良いのではないか？

**Comment by penpenpng** [comment]
ありがとうございます。 db2d53ef9130eb7951d2fbaf5a1c5ff44527506c で加筆しました。
